language: node_js
node_js:
- 6
- 7
- 8
cache:
  directories:
  - node_modules
script:
- npm test
- npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  local_dir: build
  on:
    branch: master
notifications:
  email: false
  slack:
    secure: iCv3i1emfAVMFh530MuCMhr1d2+cuQEgQM6JxVxSlQh6DmiqhOnpe20mCsITDBAb3j1WM+Zl0ZsaqbEuI3OruZ9XAQBF26WXZFRYYF6ZggFCxL4Xde15w6RGlbOIOWGSq7/4AsdljxgUrGPFjTi7pO+nawkRUUCTYuEAyNGVeaMt1evexhe8rypQ2FOp0v7e09Dhqq2MyY2waRQDHXPxrdmssWnsI+GH2BPCcTriTvw71ikpSPUVq4DbuJBK+90d9Xv9cKfbX04YdatFu4ntgJV/4qUkf0tHoWEOYz+9CaxQXZQrEk5nxH2RlMx8OG7UYIoKwvSgwBFNTd+4KMBSz+wpU7PAbB1gdkyXA8Btb6edvGpgBkkBEM/R48OlyKp8C4qAHKVcOYnq+vjCgWDttrcGyFDWxFUlXcxJtn+XKZ+iqqDjmcjqLjyslkn69ZBGjHJANJkR4hDXaTt/hhDy02HVx1yPCyrTBz17V9hrOscY2M0oIWAqv9sXcHJWPV5kNfGpQO8z1pObMgdbf5ICRIDXqrGNEa5MGe6x0M8X5o6beXGnVsHOHKY2Dxr4huFl5ea31OYQZv7u5gF7CG0INr9/hhCpoE6+9bcxyQ0KRiINJuU9ChdduxrqW+67778K1M2xu+5mixUngBgSBm2PDapyYD6jEqZ0J5Qd25Hyj9o=
